Merge pull request #54 from gregarndt/mkfs_error_handling
Prevent zombie nodes being created from filesystem creation error

diff --git a/workers/docker-worker/deploy/template/etc/default/docker-aufs b/workers/docker-worker/deploy/template/etc/default/docker-aufs
--- a/workers/docker-worker/deploy/template/etc/default/docker-aufs
+++ b/workers/docker-worker/deploy/template/etc/default/docker-aufs
@@ -1,25 +1,47 @@
-#!/bin/bash
+#!/bin/bash -vex
 
-# Find instance storage devices
-devices=$(ls /dev/xvd* | grep -v '/dev/xvda');
+# Create logical volume
+# Do not attempt to create if volume already exists (upstart respawn).
+if ! lvdisplay | grep instance_storage;
+then
+    echo "Creating logical volume 'instance_storage'"
+    # Find instance storage devices
+    devices=$(ls /dev/xvd* | grep -v '/dev/xvda');
 
-# Unmount block-device if already mounted, the first block-device always is
-for d in $devices; do umount $d || true; done
+    # Unmount block-device if already mounted, the first block-device always is
+    for d in $devices; do umount $d || true; done
 
-# Create volume group containing all instance storage devices
-echo $devices | xargs vgcreate instance_storage
+    # Create volume group containing all instance storage devices
+    echo $devices | xargs vgcreate instance_storage
 
-# Create logical volume with all storage
-lvcreate -l 100%VG -n all instance_storage
+    # Create logical volume with all storage
+    lvcreate -l 100%VG -n all instance_storage
+else
+    echo "Logical volume 'instance_storage' already exists"
+fi
+
+echo "Formating 'instance_storage' as ext4"
 
 # Format logical volume with ext4
-mkfs.ext4 /dev/instance_storage/all
+if ! mkfs.ext4 /dev/instance_storage/all;
+then
+    echo "Could not format 'instance_storage' as ext4."
+    # Wait for the logical volume to become ready to be formatted.
+    # Small wait is better than zombie node.
+    sleep 5
+    exit 1
+else
+    echo "Succesfully formated 'instance_storage' as ext4."
+fi
 
+echo "Mounting logical volume"
 # Mount on /mnt
 mount /dev/instance_storage/all /mnt
 
+echo "Creating docker specific directories"
 mkdir -p /mnt/var/lib/docker
 mkdir -p /mnt/docker-tmp
 mkdir -p /mnt/var/cache/docker-worker
+
 export TMPDIR="/mnt/docker-tmp"
 export DOCKER_OPTS=" -g /mnt/var/lib/docker -s aufs"
diff --git a/workers/docker-worker/deploy/template/etc/default/docker-btrfs b/workers/docker-worker/deploy/template/etc/default/docker-btrfs
--- a/workers/docker-worker/deploy/template/etc/default/docker-btrfs
+++ b/workers/docker-worker/deploy/template/etc/default/docker-btrfs
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -vex
 
 # Find instance storage devices
 devices=$(ls /dev/xvd* | grep -v '/dev/xvda');
@@ -6,13 +6,27 @@ devices=$(ls /dev/xvd* | grep -v '/dev/xvda');
 # Unmount block-device if already mounted, the first block-device always is
 for d in $devices; do umount $d || true; done
 
+echo "Formating 'instance_storage' as btrfs"
 # btrfsify the storage
-mkfs.btrfs -f -d single -L instance_storage $devices
 
+if ! mkfs.btrfs -f -d single -L instance_storage $devices;
+then
+    echo "Could not format 'instance_storage' as btrfs."
+    # Wait for the logical volume to become ready to be formatted.
+    # Small wait is better than zombie node.
+    sleep 5
+    exit 1
+else
+    echo "Succesfully formated 'instance_storage' as btrfs."
+fi
+
+
+echo "Mounting logical volume"
 # fetch first device btrfs can mount any of them (they are all part of the same
 # fs)
 mount $(echo $devices | cut -d ' ' -f 1) /mnt
 
+echo "Creating docker specific directories"
 mkdir -p /mnt/var/lib/docker
 mkdir -p /mnt/docker-tmp
 mkdir -p /mnt/var/cache/docker-worker
